global:
  cattle:
    systemDefaultRegistry: ""

mcp:
  readOnly: false
  env: []
  image:
    repository: rancher/harvester-mcp-server
    tag: dev
    pullPolicy: IfNotPresent

insecureSkipTls: false
seLinux:
  enabled: false

log:
  level: info
